spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop # 주의! 로컬 테스트에서만 사용한다.
  datasource:
    hikari:
      jdbc-url: jdbc:h2:./test;DB_CLOSE_DELAY=-1;MODE=MYSQL; # TRACE_LEVEL_SYSTEM_OUT=3; # h2에서 출력하는 트랜잭션 로그 확인할 때 사용
      username: sa
      password:

# 스프링에서 출력하는 트랜잭션 로그를 직접 보고 싶으면 아래 주석 해제
#logging:
#  level:
#    org.springframework.transaction.interceptor: TRACE
#    org.springframework.transaction.support: DEBUG
